/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BoatId } from './boatId';


export interface CreateReservationDTO { 
    startTime: string;
    endTime: string;
    boatId: BoatId;
}

