/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDTO } from './userDTO';
import { DebtId } from './debtId';


export interface DebtUserDTO { 
    debtId?: DebtId;
    amount?: number;
    debtStatus?: DebtUserDTO.DebtStatusEnum;
    debitor?: UserDTO;
}
export namespace DebtUserDTO {
    export type DebtStatusEnum = 'OPEN' | 'PAYED' | 'CLOSED';
    export const DebtStatusEnum = {
        Open: 'OPEN' as DebtStatusEnum,
        Payed: 'PAYED' as DebtStatusEnum,
        Closed: 'CLOSED' as DebtStatusEnum
    };
}


