/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DebtUserDTO } from './debtUserDTO';
import { UserDTO } from './userDTO';
import { PaymentId } from './paymentId';


export interface DebtPaymentDTO { 
    paymentId?: PaymentId;
    payedAt?: string;
    reason?: string;
    creditor?: UserDTO;
    debtUserDTO?: DebtUserDTO;
}

