/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentId } from './paymentId';
import { FuelPaymentPeriodDTO } from './fuelPaymentPeriodDTO';
import { UserTotalHoursDTO } from './userTotalHoursDTO';
import { UserTotalPayedDTO } from './userTotalPayedDTO';


export interface FuelInvoiceDTO { 
    fuelPaymentPeriodDTO?: FuelPaymentPeriodDTO;
    totalHours?: number;
    totalPayed?: number;
    userTotalHoursDTOs?: Array<UserTotalHoursDTO>;
    userTotalPayedDTOs?: Array<UserTotalPayedDTO>;
    paymentsCharged?: Array<PaymentId>;
}

