/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentUserDTO } from './paymentUserDTO';


export interface PagedResultListPaymentUserDTO { 
    result?: Array<PaymentUserDTO>;
    hasNext?: boolean;
    totalNumber?: number;
}

