/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DebtUserDTO } from './debtUserDTO';
import { UserDTO } from './userDTO';
import { PaymentId } from './paymentId';


export interface PaymentUserDTO { 
    paymentId?: PaymentId;
    payedAt?: string;
    amount?: number;
    reason?: string;
    isFuelPayment?: boolean;
    paymentStatus?: PaymentUserDTO.PaymentStatusEnum;
    creditor?: UserDTO;
    debitors?: Array<DebtUserDTO>;
}
export namespace PaymentUserDTO {
    export type PaymentStatusEnum = 'OPEN' | 'CHARGED' | 'CLOSED';
    export const PaymentStatusEnum = {
        Open: 'OPEN' as PaymentStatusEnum,
        Charged: 'CHARGED' as PaymentStatusEnum,
        Closed: 'CLOSED' as PaymentStatusEnum
    };
}


