/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BoatId } from './boatId';
import { ReservationId } from './reservationId';
import { UserDTO } from './userDTO';


export interface ReservationUserDTO { 
    reservationId?: ReservationId;
    startDateTime?: string;
    endDateTime?: string;
    boatHoursOnStart?: number;
    boatHoursOnEnd?: number;
    boatId?: BoatId;
    userDTO?: UserDTO;
}

