export * from './authenticationController.service';
import { AuthenticationControllerService } from './authenticationController.service';
export * from './boatController.service';
import { BoatControllerService } from './boatController.service';
export * from './readPaymentController.service';
import { ReadPaymentControllerService } from './readPaymentController.service';
export * from './readReservationController.service';
import { ReadReservationControllerService } from './readReservationController.service';
export * from './reservationController.service';
import { ReservationControllerService } from './reservationController.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export * from './writePaymentController.service';
import { WritePaymentControllerService } from './writePaymentController.service';
export const APIS = [AuthenticationControllerService, BoatControllerService, ReadPaymentControllerService, ReadReservationControllerService, ReservationControllerService, UserControllerService, WritePaymentControllerService];
