# DB
spring.datasource.url=jdbc:postgresql://localhost:5432/boatsharing
spring.datasource.username=user
spring.datasource.password=password
spring.sql.init.mode=always
# Debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# OpenApi Spec
springdoc.api-docs.path=/api-docs